// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6uE0-cz3milfseUHzhqIuu-MZaXFiUMk',
    appId: '1:561508743897:web:4d4d9cecceea4cb98cdcc8',
    messagingSenderId: '561508743897',
    projectId: 'misli-os',
    authDomain: 'misli-os.firebaseapp.com',
    storageBucket: 'misli-os.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR0aKR2BvLVP7JDFNlgdYdXbf4xgTzkbk',
    appId: '1:561508743897:android:daff89359f58aa9b8cdcc8',
    messagingSenderId: '561508743897',
    projectId: 'misli-os',
    storageBucket: 'misli-os.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXDGuK_sDjNkJP5_0uOz2fY1ACgclpPS0',
    appId: '1:561508743897:ios:6dfe079b164038898cdcc8',
    messagingSenderId: '561508743897',
    projectId: 'misli-os',
    storageBucket: 'misli-os.appspot.com',
    iosClientId: '561508743897-rm1bq5c431nslv7cmj05hasrkd0oc8ig.apps.googleusercontent.com',
    iosBundleId: 'com.example.misliOsApp',
  );
}
